extension Server {
  /// Registers the provided resources with the MCP server using the recommended handlers.
  ///
  /// The server automatically responds to `resources/list` with metadata generated by each
  /// resource's `toResource()` output and wires `resources/read` to the resource's content getter.
  ///
  /// ## Example
  ///
  /// ```swift
  /// let server = Server(
  ///   name: "Resource Server",
  ///   version: "1.0.0",
  ///   capabilities: .init(resources: .init(listChanged: true))
  /// )
  ///
  /// await server.register(resources: [
  ///   WidgetResource(),
  ///   DocumentResource()
  /// ])
  /// ```
  ///
  /// - Parameter resources: The collection of resources that should be surfaced to MCP clients.
  /// - SeeAlso: https://modelcontextprotocol.io/specification/2025-06-18/server/resources
  public func register(resources: [any MCPResource]) async {
    self.withMethodHandler(ListResources.self) { _ in
      .init(resources: resources.map { $0.toResource() })
    }

    self.withMethodHandler(ReadResource.self) { params async throws in
      guard let resource = resources.first(where: { $0.uri == params.uri }) else {
        throw MCPError.invalidRequest("Unknown resource URI: \(params.uri)")
      }

      return try await resource.read(uri: params.uri)
    }
  }
}
