import MCP

extension Server {
  /// Registers the provided tools with the MCP server using the recommended handlers.
  ///
  /// The server automatically responds to `tools/list` with metadata generated by each tool's
  /// ``MCPTool/toTool()`` output and wires `tools/call` to ``MCPTool/call(arguments:)``. This
  /// mirrors the behaviour documented in the
  /// [swift-sdk README](https://github.com/modelcontextprotocol/swift-sdk) while removing the
  /// boilerplate for JSON parsing, validation, and error reporting.
  ///
  /// - Parameter tools: The collection of tools that should be surfaced to MCP clients.
  /// - SeeAlso: https://modelcontextprotocol.io/specification/2025-06-18/server/tools
  public func register(tools: [any MCPTool]) async {
    self.withMethodHandler(ListTools.self) { _ in
      .init(tools: tools.map { $0.toTool() })
    }

    self.withMethodHandler(CallTool.self) { params async in
      guard let tool = tools.first(where: { $0.name == params.name }) else {
        return .init(
          content: [.text("Unknown tool: \(params.name)")],
          isError: true
        )
      }

      if let arguments = params.arguments {
        do {
          let result = try await tool.call(arguments: arguments)
          return result
        } catch {
          return .init(
            content: [.text("Error occurred while calling tool \(params.name): \(error)")],
            isError: true
          )
        }
      }

      return .init(
        content: [.text("Missing arguments for tool \(params.name)")],
        isError: true
      )
    }
  }
}
